version: '3'
services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    container_name: elasticsearch01
    #build: .
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - node.name=elasticsearch01
      - cluster.name=elasticsearch
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.23
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch01:9200
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - xpack.maps.showMapVisualizationTypes=true
    networks:
      - elk
    depends_on:
      - elasticsearch01

networks:
  elk:
    driver: bridge
